title = "H$T"
baseURL = "https://insane-csc-site.netlify.app/"
languageCode = 'en-us'
theme = "ananke"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = false

[services.googleAnalytics]
    id = ''




[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    custom_css = ["custom.css"]
    mainSections = ["post"]
    text_color = ""

    favicon = ""
    site_logo = ""
    background_color_class = "bg-black"
    featured_image_class = "cover bg-top"
    cover_dimming_class = "bg-black-60"
    recent_posts_number = 3


[params.ananke.social.share]
networks = [
  "instagram"  # Nur Instagram zum Teilen hinzufügen
]

[params.ananke.social.follow]
networks = [
  "instagram"  # Nur Instagram zum Folgen hinzufügen
]

# Instagram Konfiguration
[params.ananke.social.instagram]
username = "dein_instagram_username"  # Dein Instagram-Benutzername hier eintragen
profilelink = "https://www.instagram.com/dein_instagram_username"  # Instagram-Profillink
